### ISSUE TITLE
Literature Review on Recommender Systems

### ISSUE THREAD

**Issue by snehathth** [snehathth/Big-data-Yelp-Recommender-System#1]
There are basically 2 types of recommender systems. Content based and collaborative. Find out codes, algorithms and reports on such recommender systems. Best place to start would be kaggle

Check https://www.kaggle.com/yelp-dataset/yelp-dataset Kernels as a starter and get as much details on active, positive looking projects

**Comment by Anaghakatthe** [comment]
[LITERATURE REVIEW FOR RECOMMEDER SYSTEM FOR YELP DATASET.docx](https://github.com/snehathth/Big-data-Yelp-Recommender-System/files/3769541/LITERATURE.REVIEW.FOR.RECOMMEDER.SYSTEM.FOR.YELP.DATASET.docx)
